### ISSUE TITLE
Switch Expression

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#112]
This lovechild of the switch and lambda syntacies could be a nice shorthand:
```LUA
local function int2eng(i)
    return switch i do
        case 1 -> "One"
        case 2 -> "Two"
        default -> "Other"
    end
end
```
This should be unambigious to parse, tho I assume generating (efficient) code for this is gonna be a challenge.

**Comment by NotSoSeriouss** [comment]
> This lovechild of the switch and lambda syntacies could be a nice shorthand:
> 
> ```lua
> local function int2eng(i)
>     return switch i do
>         case 1 -> "One"
>         case 2 -> "Two"
>         default -> "Other"
>     end
> end
> ```
> 
> This should be unambigious to parse, tho I assume generating (efficient) code for this is gonna be a challenge.

I don't think it's hard to make efficent code for it. Switches are one of the most efficent selections in programming since they use hashmaps. In Vanilla Lua you can make a switch like this:
```Lua
local switch = {
    [1] = function() return "One" end,
    [2] = function() return "Two" end,
    ["a"] = function() return "A" end,
    ["b"] = function() return "B" end
}

local case = "a" -- 1, 2 or "a", "b"
switch[case]()
```

As you can see, Lua comes basically with hashmaps built in, so making a switch statement for Pluto could be as easy as a "Pluto to Lua" conversion

**Comment by Sainan** [comment]
Mind you, Pluto already has switch _statements_, and the code that is generated for that is far more efficient than what you just presented.
