### ISSUE TITLE
Accept expressions within interpolated strings

### ISSUE THREAD

**Issue by well-in-that-case** [PlutoLang/Pluto#196]

**Comment by Sainan** [comment]
If you mean Lua expressions, this would require throwing out the current implementation and doing it in the lexer instead, which I am not entirely against, but I'm not sure if this is syntactically the right idea, since similar format strings have their own sort of "formatting rules" syntax.

If you do mean "formatting rules", maybe some examples/a checklist?

**Comment by well-in-that-case** [comment]
My desire for f-strings is essentially identical to how Python has implemented them. Needing this:
```lua
local abc = table.key
print($"key name: {abc}")
```
is cumbersome, as opposed to:
```lua
print($"key name: {table.key}")
```

**Comment by Sainan** [comment]
Yeah, if you mean the string interpolation from Python that would almost certainly have to be done in the lexer.

Although I do prefer the str.format syntax for string formatting.

**Comment by well-in-that-case** [comment]
Oh yes, another idea I've had is that if the content within two brackets is an invalid expression, we ignore formatting entirely and parse that substring as plain text.
```lua
local string = "abc"
local value = 5
$"{ hashFunction("{string}", {value} }"
-- would only format {string} & {value}
-- "{ hashFunction("abc"), 5 }"
```
This is a bit easier said than done though, since the parser is designed to throw errors immediately upon problems, instead of an expr function returning "false" or something to indicate bad status.
