### ISSUE TITLE
New switch feature makes tables unable to have a key named "default"

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#20]
Understandable if you don't want to fix this, but does slightly break backward-compatbility.

**Comment by well-in-that-case** [comment]
They can still contain the key provided they don't try and access it with syntactic sugar. Accessing and assigning the key with brackets, or with expressions will still work. Not sure if I can make a special case for syntactic sugar, _but_ if I can, then I probably will.

**Comment by Sainan** [comment]
```LUA
t = {
	default = nil
}
```
> test.lua:2: syntax error: unexpected symbol near 'default'
         2 | default
           | ^^^^^^^ here: unexpected symbol.
           |

**Comment by well-in-that-case** [comment]
Users can vouch for
```lua
t = {
	["default"] = nil
}
```
and it'll work, but it's true that this is an incompatibility. I do think we may be able to address this with lookahead tokens when we read TK_DEFAULT (maybe in the sense that TK_CASE will error?), but no promises on my side. To a more extreme sense, we could conform to Perl's switch syntax by using the else token instead of default, which would look worse for me but preserve compatibility.
