### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by UltraBlackLinux** [PlutoLang/Pluto#259]
Hey there,

Would you mind creating an AUR package for this? I'm not very fond of installing things that I can't easily uninstall.

I really like the idea and would like to try what this has to offer though!

Thanks!

**Comment by Sainan** [comment]
While making packages for easier installation of Pluto is on our radar, I don't see what you mean by "things that I can't easily uninstall". In principle, you can drop the pluto and plutoc executables anywhere, including a folder that's in your path — that's a state I might call "installed" — but it would be just as easy to delete the executables again.

**Comment by UltraBlackLinux** [comment]
the issue with running e.g. `make install` is that you need the makefile (and a rule) to uninstall it again, otherwise you end up with orphan files on your system.

It generally makes sense to be able to add the executable to your `PATH`, which is why I even bring this up

**Comment by Sainan** [comment]
I see. We only have a makefile because of Lua legacy iirc, it's completely unreadable and unmodifyable in my eyes. So my suggestion for getting started with Pluto (outside of using the interactive web playground nor pre-built binaries) would be to compile Pluto either with make, Sun, or the PHP scripts, and then drop executable(s) where ever you see fit.

**Comment by Sainan** [comment]
Going to track this in #274
