### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#274]
To make it easier for people to get Pluto on their machines.

- [X] Chocolatey
- [x] `.deb` package
- [ ] AUR package (no idea what format this uses; AUR is the place to submit it?)

**Comment by UltraBlackLinux** [comment]
Creating packages on arch is not too hard. The AUR uses pkgbuilds (essentially nicely wrapped build and install scripts), which are extensively documented [here](https://wiki.archlinux.org/title/Creating_packages). For examples, head over to aur.archlinux.org, find any package, and click the "View PKGBUILD" button on the right

Edit: I tried to create a pluto pkgbuild, but gave up when I could not easily switch away from mingw. In my opinion it's just another C/C++ compiler, which most people don't need, if they are running linux since compilers like g++, gcc and clang are probably already installed.

<details><summary>Here is what I have come up with</summary>

```bash
pkgname=pluto-lang-git
pkgver=r1026.03abc01
pkgrel=1
pkgdesc="A superset of Lua 5.4 — with unique features, optimizations, and improvements."
arch=('any')
url='https://github.com/PlutoLang/Pluto'
license=('MIT')
depends=('make')
makedepends=('git')
optdepends=('')
source=("${pkgname}::git+https://github.com/PlutoLang/Pluto.git")
sha256sums=('SKIP')

pkgver() {
  cd ${pkgname}
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

package() {
  cd "${srcdir}/${pkgname}"
  make -e "PLATS=g++" all
  make -e "INSTALL_TOP=\"${pkgdir}\"" install
}
```
</details>

**Comment by Sainan** [comment]
I'm not sure why you would use mingw on Arch Linux? I thought that's a Windows program?

Also, Pluto is versioned, our latest version is 0.6.2 at commit bff6daf4a062c65fb1ad46d517b029bd7720f936.

**Comment by UltraBlackLinux** [comment]
Mingw is also available on linux, but the makefile does not allow anything else, and I have no idea what to edit.

Regarding the hash: Yeah, I know. the makefile does not work right now anyways.

**Comment by Sainan** [comment]
Well, as stated in the other thread, I don't like make exactly because it's so unreadable. It also doesn't really resolve any problems for us. I think if you added 'php' to makedeps, you could simply run the relevant PHP build scripts in "package()":
```
php scripts/compile.php clang
php scripts/link_pluto.php clang
php scripts/link_plutoc.php clang
```

**Comment by Sainan** [comment]
So, I did manage to get a `.deb` package sorted out for Pluto. As for Arch... I can't get Arch running in a VM. I can't get PopOS running in a VM. I *did* manage to get Linux Mint running in a VM, but it seems C++ 11 was the most recent thing the compiler recognised, which is just... waaaay too old. This distro seems completely unusable.

**Comment by Sainan** [comment]
I have managed to make a PKGBUILD file based on what has been shared/discussed here so far: https://github.com/PlutoLang/Pluto/blob/5df09d5831b1deb4a001260841478a1b6e7fa9e4/PKGBUILD

You are free to use this with `makepkg` then `sudo pacman -U` the produced file. As I am not able to automate this and I am not an avid Arch Linux user, this is probably gonna be as far as I will go on this.
