### ISSUE TITLE
Pluto REPL does not detect incomplete statements

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#399]
![image](https://github.com/PlutoLang/Pluto/assets/63328889/5643210d-b4b2-4ad8-9c35-6a9a2d789c20)

Lua would mention `<eof>` in the error message, which we don't. We could fix this by maybe detecting the token being `<eof>` and printing "incomplete statement", which we could then use to detect incomplete statements in the REPL.

**Comment by well-in-that-case** [comment]
I didn't notice this ticket until I already pushed my fix to main but the solution is similar. Instead of making any real changes to our error messages I just slapped (near %s) back onto them like OG lua already has. Doesn't take away or add value which is probably preferable.

The code snippet logic I included in that commit is needed either way whenever we do substring searches.
