### ISSUE TITLE
io.basename or io.filename

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#503]
Sort of the opposite of io.parent, i.e. for `/path/to/foo.txt`, the parent is `/path/to` and the basename is `foo.txt`.

**Comment by well-in-that-case** [comment]
Before io.parent is introduced in 0.8.0, we might be able to designate a function to handle both the parent directory and the filename, since it's essentially partitioning a filepath by the last component. This is probably preferable to making the users partition the path themselves (maybe via an `io.path`) since people would need to handle Windows.

Tricky part is a short name which can express that purpose.

**Comment by Sainan** [comment]
How about `io.part`?
```Lua
print(io.part("/path/to/foo.txt", "parent")) -- /path/to
print(io.part("/path/to/foo.txt", "name")) -- foo.txt
```
Could also be extended with like "ext".

**Comment by well-in-that-case** [comment]
`part` is a decent one, could consider going as far as straight up `io.partition` too. Slightly preferable to me but not sure if that's something beginners might get a little confused with.

**Comment by Sainan** [comment]
I mean "part" as in the noun.
