### ISSUE TITLE
table.checkall

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#514]
Checks if every element in the table fits the criteria provided by the function:
```Lua
local t = { 1, 3, 5 }
assert(t:every(|x| -> x % 2 != 0))
```

**Comment by well-in-that-case** [comment]
Kind of possible with `table.foreach` already. This function halts execution and returns the return value of the callback if the callback returns a non-nil value. I'd argue Lua made a bit of a mistake here because `foreach` will need to return a falsy value (nil when all conditions pass) to serve as something like this and that's unintuitive. But sadly we cannot add our own behavior here because this was intentional from Lua and someone might be relying on it.

```lua
print({ 1, 2, 3, hello = "a" }:foreach(function (key, value)
	if type(key) ~= "number" then
		return false
	end
end) == nil)
```

Anyway, we'd need a more intuitive name. Maybe `table.checkall` or something.

**Comment by Sainan** [comment]
`table.foreach` serves a different purpose. I just took `every` because that's what JS calls it.

**Comment by Sainan** [comment]
`satisfies` or `allsatisfy` might also be good names for this
