### ISSUE TITLE
Any plan to support Rust integration?

### ISSUE THREAD

**Issue by linux-china** [PlutoLang/Pluto#772]
I have submitted https://github.com/mlua-rs/mlua/issues/354 to integrate Pluto with Rust, and nobody answers. 
Any plan to supply Rust binding for Pluto. Now lots of CLI tools written by Rust, and I want to integrate Pluto in my project to enhance Lua features.

**Comment by Sainan** [comment]
Providing language-specific bindings is a bit out of scope for us. Probably the closest to that we have done is [PlutoScript](https://github.com/PlutoLang/PlutoScript), but that's also just using the C API via an FFI layer. Even when we integrate Pluto in C++, we use the C API directly without any abstractions/bindings. The same should be possible in Rust:
```rust
#[link(...)]
extern {
    fn luaL_newstate() -> *mut lua_State;
    // ...
}

fn main() {
    unsafe {
        let L = luaL_newstate();
        println!("Allocated lua state @ {:p}", L);
        // ...
    }
}
```
I understand the 'unsafe' part is probably undesirable, but I'm not sure how much safety can be assured when working with the Lua C API since there's many ways to mess up and crash with it, esp. in regards to Lua stack corruption.
