### ISSUE TITLE
Enable compatibility mode on `.lua` files.

### ISSUE THREAD

**Issue by asumbek** [PlutoLang/Pluto#812]
Enable compatibility mode on `.lua` files. By mean when a Pluto script `require`s a `.lua` file, it'll enable compatibility mode on that file but not on the Pluto script. This is much better than having `--@pluto_use` on every single Lua files that has preserved keywords or operators.

```lua
-- module.lua

local enum = {  -- `enum` is preserved keyword
  MY_ENUM = 1,
}

return {
  enums = enum,
}
```
```lua
-- main.pluto

local module = require("module") -- when requiring module, Pluto will not complain about preserved keywords because compatibility is enabled in `module.lua`

print(module.enums.MY_ENUM)
```

**Comment by Sainan** [comment]
We do something similar in our embedded Pluto environment, but not to the extreme of ".lua = keywords off, .pluto = keywords on" because people are (perhaps unsurprisingly) not particularly explicit about differentiating between Lua and Pluto with the file extensions.

I understand your use-case probably is using Pluto on the CLI with an existing Lua codebase, but I'm afraid some combination of the '-c' argument and `pluto_use` will always be needed.

**Comment by Sainan** [comment]
I'm gonna supersede this with #813.
