### ISSUE TITLE
Requesting new feature 'async'.

### ISSUE THREAD

**Issue by baidwwy** [PlutoLang/Pluto#848]
https://github.com/ms-jpq/lua-async-await

**Comment by Sainan** [comment]
I don't get it. Lua already has coroutines, and Pluto already has [the scheduler library](https://pluto-lang.org/docs/Runtime%20Environment/Scheduler) to reduce the boilerplate around using them.

Furthermore, the way we design our standard library is so that it can be used in both blocking and non-blocking ways, so I just don't see what problem this is trying to solve.
