### ISSUE TITLE
[Deferred] Add `flake.nix`

### ISSUE THREAD

**Issue by asumbek** [PlutoLang/Pluto#936]
Building on NixOS requires a `flake.nix`.

<sub>Tagging this as "deferred" as it's not an important issue</sub>

**Comment by Sainan** [comment]
What?

**Comment by asumbek** [comment]
Context: NixOS doesn't follow FHS standard unlike any other Linux distros, instead it stores in `/nix` directory which where all the headers, libraries, etc. are stored. This makes building everything on NixOS quite impossible, unless there's `flake.nix` which handles all the headers and libraries to be available.

One of example that do this is Helix editor ([`flake.nix`](https://github.com/helix-editor/helix/blob/master/flake.nix)).

**Comment by Sainan** [comment]
You are free to contribute this yourself, but we aim for UNIX support by using POSIX APIs and such. How exactly you compile and store the binary is a bit out-of-scope.

**Comment by asumbek** [comment]
> You are free to contribute this yourself, but we aim for UNIX support by using POSIX APIs and such. How exactly you compile and store the binary is a bit out-of-scope.

It's only a feature for NixOS and Nix, Nix itself support variety of POSIX-compliant OSes. But if you don't want to, that's alright.

**Comment by Sainan** [comment]
Well, if Nix is POSIX compliant, and Pluto is POSIX compliant, then I think all is good. :)

**Comment by alerque** [comment]
Having a Nix Flake or not is **totally unrelated to POSIX compliance**! I don't know what either of you are going on about but that's completely unrelated. Having a `flake.nix` serves the purpose of being able to use the *repository* (at any arbitrary tag/branch/commit) as a Nix project (package, user config, project) dependency, to execute it directly without needing to download/configure/make/install anything at all. Additionally it can provide a consistent developer environment for anybody that wants one without getting in the way of the project development at all. This various functions can be quite handy for projects, CI runners, etc. To work it needs to be in *this* repository so that it's versioned along with the code it is building. Separately the Nix packages project can package Pluto as well at fixed versions (typically when the project is tagged), but that's also orthogonal to having a flake or not.

**Comment by Sainan** [comment]
I don't quite see how you are going to _execute_ Pluto given only C/C++ source files and seemingly no requirement to "make" it.

And, again, I would be perfectly happy accepting a PR to upstream a `flake.nix` file if you did want it in this repository.
