### ISSUE TITLE
Method shorthand discrepancy

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#95]
```LUA
local t = {
    f = function(str)
        print(str)
    end
}
t.f("hi")
```
This code prints "hi", as expected, but trying to replace this with the following shorthand syntax:
```LUA
local t = {
    function f(str)
        print(str)
    end
}
t.f("hi")
```
causes this code to print "nil", because the first argument is seemingly put into `self`, instead.

**Comment by well-in-that-case** [comment]
The keyword here is shorthand method syntax. 'f' is not a method, it's a normal function in this instance. The syntactic sugar is a method, so that the first example is only 1:1 if the first argument is self. This might need to be documented better, but it's a major syntactic ambiguity that I wouldn't of noticed if I didn't make the feature myself.

**Comment by well-in-that-case** [comment]
Fyi:
I'm still going to try and improve this behavior by changing the syntax. I'll keep the thread updated.

**Comment by well-in-that-case** [comment]
The website has been updated to place emphasis on the syntax. I'm fairly unconfident I can make a good change to the syntax itself though, since a change requiring (i.e) "explicit parameters" for methods is a breaking change.

**Comment by Sainan** [comment]
No change is needed imo, if you say how it currently works is as intended.
